name: Ebbterra
favicon: null
layout_spectrum: 0.35984238306991756
typography_spectrum: 0.004242263501510024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5812529923859984
  lightness: 0.7185694240033627
  saturation: 0.9210200181696564
  rhythmicContrast: 0.9223295080009848
purpose: []
